import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { PieChartStat } from "../../elements";
import { sampleData, useDocumentTitle } from "../../../utils/helper";
import { MdOutlineDriveFileRenameOutline } from "react-icons/md";
const StudentReportLearning = () => {
    const [tab, setTab] = useState("tutor");
    useDocumentTitle("Tiến độ học tập");
    return (_jsxs("div", { className: "student-report-learning", children: [_jsxs("div", { className: "tabs", children: [_jsxs("div", { className: `tab ${tab === "tutor" ? "active" : ""}`, onClick: () => setTab("tutor"), children: ["Gia s\u01B0", _jsx("span", { className: `underline left ${tab === "tutor" ? "full" : ""}` }), _jsx("span", { className: `underline right ${tab === "tutor" ? "full" : ""}` })] }), _jsxs("div", { className: `tab ${tab === "class" ? "active" : ""}`, onClick: () => setTab("class"), children: ["L\u1EDBp h\u1ECDc", _jsx("span", { className: `underline left ${tab === "class" ? "full" : ""}` }), _jsx("span", { className: `underline right ${tab === "class" ? "full" : ""}` })] })] }), tab === "tutor" && _jsxs(_Fragment, { children: [_jsxs("div", { className: "form-field", children: [_jsx("label", { className: "form-label", children: "Ch\u1ECDn gia s\u01B0" }), _jsxs("div", { className: "form-input-container", children: [_jsx(MdOutlineDriveFileRenameOutline, { className: "form-input-icon" }), _jsxs("select", { name: "", id: "", className: "form-input", children: [_jsx("option", { value: "", children: "-- Ch\u1ECDn gia s\u01B0 --" }), _jsx("option", { value: "", children: "Nam" }), _jsx("option", { value: "", children: "N\u1EEF" })] })] })] }), _jsx(PieChartStat, { data: sampleData })] }), tab === "class" && _jsxs(_Fragment, { children: [_jsxs("div", { className: "form-field", children: [_jsx("label", { className: "form-label", children: "Ch\u1ECDn l\u1EDBp h\u1ECDc" }), _jsxs("div", { className: "form-input-container", children: [_jsx(MdOutlineDriveFileRenameOutline, { className: "form-input-icon" }), _jsxs("select", { name: "", id: "", className: "form-input", children: [_jsx("option", { value: "", children: "-- Ch\u1ECDn l\u1EDBp h\u1ECDc --" }), _jsx("option", { value: "", children: "Nam" }), _jsx("option", { value: "", children: "N\u1EEF" })] })] })] }), _jsx(PieChartStat, { data: sampleData })] })] }));
};
export default StudentReportLearning;
