import { appSlice } from "../services/app/appSlice";
import { RegisterTutorState } from "../services/auth/registerTutorSlice";
import { AuthState } from "../types/auth";
import { ParentForAdminState, StudentForAdminState, TutorForAdminState } from "../types/admin";
import { AvailabilityBlockForTutorState } from "../types/tutorAvailabilityBlock";
import { BookingForTutorState, PublicTutorState, RequestFindTutorForTutorState, ScheduleForTutorState, TutorClassState } from "../types/tutor";
import { TutorScheduleState } from "../types/booking";
import { UserState } from "../types/user";
import { ChildAccountState } from "../types/parent";
import { ApplyRequestFindTutorForStudentState, BookingTutorStudentState, learningScheduleForStudentState, StudentClassState } from "../types/student";
import { PublicClassState } from "../types/public";
import { NotificationState } from "../types/notification";
import { WalletState } from "../types/wallet";
import { FeedbackState } from "../types/feedback";
import { FavoriteTutorState } from "../types/favorite-tutor";
declare const reducer: import("redux").Reducer<{
    app: import("../types/app").AppGlobalState;
    auth: AuthState;
    registerTutor: RegisterTutorState;
    tutorForAdmin: TutorForAdminState;
    studentForAdmin: StudentForAdminState;
    parentForAdmin: ParentForAdminState;
    availabilityBlockForTutor: AvailabilityBlockForTutorState;
    publicTutor: PublicTutorState;
    tutorSchedule: TutorScheduleState;
    user: UserState;
    childAccount: ChildAccountState;
    bookingTutorStudent: BookingTutorStudentState;
    bookingForTutor: BookingForTutorState;
    scheduleForTutor: ScheduleForTutorState;
    learningScheduleForStudent: learningScheduleForStudentState;
    requestFindTutorForTutor: RequestFindTutorForTutorState;
    requestFindTutorForStudent: ApplyRequestFindTutorForStudentState;
    tutorClass: TutorClassState;
    publicClass: PublicClassState;
    studentClass: StudentClassState;
    notification: NotificationState;
    wallet: WalletState;
    feedback: FeedbackState;
    favoriteTutor: FavoriteTutorState;
}, import("redux").UnknownAction, Partial<{
    app: import("../types/app").AppGlobalState | undefined;
    auth: AuthState | undefined;
    registerTutor: RegisterTutorState | undefined;
    tutorForAdmin: TutorForAdminState | undefined;
    studentForAdmin: StudentForAdminState | undefined;
    parentForAdmin: ParentForAdminState | undefined;
    availabilityBlockForTutor: AvailabilityBlockForTutorState | undefined;
    publicTutor: PublicTutorState | undefined;
    tutorSchedule: TutorScheduleState | undefined;
    user: UserState | undefined;
    childAccount: ChildAccountState | undefined;
    bookingTutorStudent: BookingTutorStudentState | undefined;
    bookingForTutor: BookingForTutorState | undefined;
    scheduleForTutor: ScheduleForTutorState | undefined;
    learningScheduleForStudent: learningScheduleForStudentState | undefined;
    requestFindTutorForTutor: RequestFindTutorForTutorState | undefined;
    requestFindTutorForStudent: ApplyRequestFindTutorForStudentState | undefined;
    tutorClass: TutorClassState | undefined;
    publicClass: PublicClassState | undefined;
    studentClass: StudentClassState | undefined;
    notification: NotificationState | undefined;
    wallet: WalletState | undefined;
    feedback: FeedbackState | undefined;
    favoriteTutor: FavoriteTutorState | undefined;
}>>;
export type RootState = {
    app: ReturnType<typeof appSlice.reducer>;
    auth: AuthState;
    registerTutor: RegisterTutorState;
    tutorForAdmin: TutorForAdminState;
    studentForAdmin: StudentForAdminState;
    parentForAdmin: ParentForAdminState;
    availabilityBlockForTutor: AvailabilityBlockForTutorState;
    publicTutor: PublicTutorState;
    tutorSchedule: TutorScheduleState;
    user: UserState;
    childAccount: ChildAccountState;
    bookingTutorStudent: BookingTutorStudentState;
    bookingForTutor: BookingForTutorState;
    scheduleForTutor: ScheduleForTutorState;
    learningScheduleForStudent: learningScheduleForStudentState;
    requestFindTutorForTutor: RequestFindTutorForTutorState;
    requestFindTutorForStudent: ApplyRequestFindTutorForStudentState;
    tutorClass: TutorClassState;
    publicClass: PublicClassState;
    studentClass: StudentClassState;
    notification: NotificationState;
    wallet: WalletState;
    feedback: FeedbackState;
    favoriteTutor: FavoriteTutorState;
};
export default reducer;
