import type { ParentForAdmin, ParentsForAdmin, StudentForAdmin, StudentsForAdmin, TutorForAdmin, TutorsForAdmin } from "../types/admin";
import type { Selector } from "../types/app";
import type { TutorSchedules } from "../types/booking";
import type { CheckFavoriteTutorRessponse } from "../types/favorite-tutor";
import type { FeedbackInTutorProfileResponse } from "../types/feedback";
import type { NotificationResponseItem } from "../types/notification";
import type { ChildAccount, ChildAccounts } from "../types/parent";
import type { PublicClass } from "../types/public";
import type { ApplyRequestFindTutorForStudent, AssignedClassForStudent, ClassRequests, learningScheduleForStudent } from "../types/student";
import type { ApplyrequestFindTutorForTutor, BookingForTutor, PublicTutor, PublicTutors, RequestFindTutorForTutor, ResponsePublicTutors, ScheduleForTutor, StudentEnrolledClassForTutor, TutorClass, TutorProfile } from "../types/tutor";
import type { AvailabilityBlocksForTutor } from "../types/tutorAvailabilityBlock";
import type { ParentProfile, ProfileStudent, UserInfoLogin } from "../types/user";
import type { WalletBalance, WalletTransactionHistoryResponse } from "../types/wallet";
export declare const selectUserLogin: Selector<UserInfoLogin | null>;
export declare const selectIsAuthenticated: Selector<boolean>;
export declare const selectToken: Selector<string | null>;
export declare const selectListTutorsForAdmin: Selector<TutorsForAdmin[] | null>;
export declare const selectTutorForAdmin: Selector<TutorForAdmin | null>;
export declare const selectListStudentsForAdmin: Selector<StudentsForAdmin[] | null>;
export declare const selectStudentForAdmin: Selector<StudentForAdmin | null>;
export declare const selectListParentsForAdmin: Selector<ParentsForAdmin[] | null>;
export declare const selectParentForAdmin: Selector<ParentForAdmin | null>;
export declare const selectListAvailabilityBlockForTutor: Selector<AvailabilityBlocksForTutor[] | null>;
export declare const selectListBookingForTutor: Selector<BookingForTutor[] | null>;
export declare const selectDetailBookingForTutor: Selector<BookingForTutor | null>;
export declare const selectListScheduleForTutor: Selector<ScheduleForTutor[] | null>;
export declare const selectListRequestFindTutorForTutor: Selector<RequestFindTutorForTutor[] | null>;
export declare const selectDetailRequestFindTutorForTutor: Selector<RequestFindTutorForTutor | null>;
export declare const selectListApplyRequestFindTutorForTutor: Selector<ApplyrequestFindTutorForTutor[] | null>;
export declare const selectListTutorClass: Selector<TutorClass[] | null>;
export declare const selectDetailTutorClass: Selector<TutorClass | null>;
export declare const selectListStudentEnrolledClassFortutor: Selector<StudentEnrolledClassForTutor[] | null>;
export declare const selectListPublicTutors: Selector<ResponsePublicTutors<PublicTutors[]> | null>;
export declare const selectPublicTutor: Selector<PublicTutor | null>;
export declare const selectListPublicClasses: Selector<PublicClass[] | null>;
export declare const selectDetailPublicClass: Selector<PublicClass | null>;
export declare const selectListTutorSchedule: Selector<TutorSchedules[] | null>;
export declare const selectProfileTutor: Selector<TutorProfile | null>;
export declare const selectProfileParent: Selector<ParentProfile | null>;
export declare const selectProfileStudent: Selector<ProfileStudent | null>;
export declare const selectListChildAccount: Selector<ChildAccounts[] | null>;
export declare const selectDetailChildAccount: Selector<ChildAccount | null>;
export declare const selectListClassRequestForStudent: Selector<ClassRequests[] | null>;
export declare const selectDetailClassRequestForStudent: Selector<ClassRequests | null>;
export declare const selectListLearningScheduleForStudent: Selector<learningScheduleForStudent[] | null>;
export declare const selectListApplyRequestFindTutorForStudent: Selector<ApplyRequestFindTutorForStudent[] | null>;
export declare const selectIsEnrolledClassForStudent: Selector<boolean>;
export declare const selectListAssignedClassForStudent: Selector<AssignedClassForStudent[] | null>;
export declare const selectNotifications: Selector<NotificationResponseItem[]>;
export declare const selectBalance: Selector<WalletBalance | null>;
export declare const selectListTransactionHistory: Selector<WalletTransactionHistoryResponse | null>;
export declare const selectListFeedbackInTutorProfile: Selector<FeedbackInTutorProfileResponse | null>;
export declare const selectCheckFavoriteTutor: Selector<CheckFavoriteTutorRessponse | null>;
