import type { TypedUseSelectorHook } from "react-redux";
import { type RootState } from "./reducer";
export declare const store: import("@reduxjs/toolkit").EnhancedStore<{
    app: import("../types/app").AppGlobalState;
    auth: import("../types/auth").AuthState;
    registerTutor: import("../services/auth/registerTutorSlice").RegisterTutorState;
    tutorForAdmin: import("../types/admin").TutorForAdminState;
    studentForAdmin: import("../types/admin").StudentForAdminState;
    parentForAdmin: import("../types/admin").ParentForAdminState;
    availabilityBlockForTutor: import("../types/tutorAvailabilityBlock").AvailabilityBlockForTutorState;
    publicTutor: import("../types/tutor").PublicTutorState;
    tutorSchedule: import("../types/booking").TutorScheduleState;
    user: import("../types/user").UserState;
    childAccount: import("../types/parent").ChildAccountState;
    bookingTutorStudent: import("../types/student").BookingTutorStudentState;
    bookingForTutor: import("../types/tutor").BookingForTutorState;
    scheduleForTutor: import("../types/tutor").ScheduleForTutorState;
    learningScheduleForStudent: import("../types/student").learningScheduleForStudentState;
    requestFindTutorForTutor: import("../types/tutor").RequestFindTutorForTutorState;
    requestFindTutorForStudent: import("../types/student").ApplyRequestFindTutorForStudentState;
    tutorClass: import("../types/tutor").TutorClassState;
    publicClass: import("../types/public").PublicClassState;
    studentClass: import("../types/student").StudentClassState;
    notification: import("../types/notification").NotificationState;
    wallet: import("../types/wallet").WalletState;
    feedback: import("../types/feedback").FeedbackState;
    favoriteTutor: import("../types/favorite-tutor").FavoriteTutorState;
} & import("redux-persist/es/persistReducer").PersistPartial, import("redux").UnknownAction, import("@reduxjs/toolkit").Tuple<[import("redux").StoreEnhancer<{
    dispatch: import("redux-thunk").ThunkDispatch<{
        app: import("../types/app").AppGlobalState;
        auth: import("../types/auth").AuthState;
        registerTutor: import("../services/auth/registerTutorSlice").RegisterTutorState;
        tutorForAdmin: import("../types/admin").TutorForAdminState;
        studentForAdmin: import("../types/admin").StudentForAdminState;
        parentForAdmin: import("../types/admin").ParentForAdminState;
        availabilityBlockForTutor: import("../types/tutorAvailabilityBlock").AvailabilityBlockForTutorState;
        publicTutor: import("../types/tutor").PublicTutorState;
        tutorSchedule: import("../types/booking").TutorScheduleState;
        user: import("../types/user").UserState;
        childAccount: import("../types/parent").ChildAccountState;
        bookingTutorStudent: import("../types/student").BookingTutorStudentState;
        bookingForTutor: import("../types/tutor").BookingForTutorState;
        scheduleForTutor: import("../types/tutor").ScheduleForTutorState;
        learningScheduleForStudent: import("../types/student").learningScheduleForStudentState;
        requestFindTutorForTutor: import("../types/tutor").RequestFindTutorForTutorState;
        requestFindTutorForStudent: import("../types/student").ApplyRequestFindTutorForStudentState;
        tutorClass: import("../types/tutor").TutorClassState;
        publicClass: import("../types/public").PublicClassState;
        studentClass: import("../types/student").StudentClassState;
        notification: import("../types/notification").NotificationState;
        wallet: import("../types/wallet").WalletState;
        feedback: import("../types/feedback").FeedbackState;
        favoriteTutor: import("../types/favorite-tutor").FavoriteTutorState;
    } & import("redux-persist/es/persistReducer").PersistPartial, undefined, import("redux").UnknownAction>;
}>, import("redux").StoreEnhancer]>>;
export declare const persistor: import("redux-persist").Persistor;
export type AppDispatch = typeof store.dispatch;
export declare const useAppDispatch: () => AppDispatch;
export declare const useAppSelector: TypedUseSelectorHook<RootState>;
