import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { PieChartStat } from "../../elements";
import { sampleData, useDocumentTitle } from "../../../utils/helper";
import { MdOutlineDriveFileRenameOutline } from "react-icons/md";
const ParentChildReportLearning = () => {
    const [tab, setTab] = useState("tutor");
    useDocumentTitle("Báo cáo tiến độ học tập của con");
    return (_jsxs("div", { className: "parent-child-report-learning", children: [_jsx("div", { className: "form", children: _jsxs("div", { className: "form-field", children: [_jsx("label", { className: "form-label", children: "L\u1EDBp" }), _jsxs("div", { className: "form-input-container", children: [_jsx(MdOutlineDriveFileRenameOutline, { className: "form-input-icon" }), _jsxs("select", { className: "form-input", children: [_jsx("option", { value: "", children: "Ph\u1EA1m C\u00F4ng L\u00EA Tu\u1EA5n" }), _jsx("option", { value: "", children: "Nguy\u1EC5n Th\u1ECB Y\u1EBFn Vy" })] })] })] }) }), _jsxs("div", { className: "tabs", children: [_jsxs("div", { className: `tab ${tab === "tutor" ? "active" : ""}`, onClick: () => setTab("tutor"), children: ["Gia s\u01B0", _jsx("span", { className: `underline left ${tab === "tutor" ? "full" : ""}` }), _jsx("span", { className: `underline right ${tab === "tutor" ? "full" : ""}` })] }), _jsxs("div", { className: `tab ${tab === "class" ? "active" : ""}`, onClick: () => setTab("class"), children: ["L\u1EDBp h\u1ECDc", _jsx("span", { className: `underline left ${tab === "class" ? "full" : ""}` }), _jsx("span", { className: `underline right ${tab === "class" ? "full" : ""}` })] })] }), tab === "tutor" && (_jsxs(_Fragment, { children: [_jsxs("div", { className: "form-field", children: [_jsx("label", { className: "form-label", children: "Ch\u1ECDn gia s\u01B0" }), _jsxs("div", { className: "form-input-container", children: [_jsx(MdOutlineDriveFileRenameOutline, { className: "form-input-icon" }), _jsxs("select", { name: "", id: "", className: "form-input", children: [_jsx("option", { value: "", children: "-- Ch\u1ECDn gia s\u01B0 --" }), _jsx("option", { value: "", children: "Nam" }), _jsx("option", { value: "", children: "N\u1EEF" })] })] })] }), _jsx(PieChartStat, { data: sampleData })] })), tab === "class" && (_jsxs(_Fragment, { children: [_jsxs("div", { className: "form-field", children: [_jsx("label", { className: "form-label", children: "Ch\u1ECDn l\u1EDBp h\u1ECDc" }), _jsxs("div", { className: "form-input-container", children: [_jsx(MdOutlineDriveFileRenameOutline, { className: "form-input-icon" }), _jsxs("select", { name: "", id: "", className: "form-input", children: [_jsx("option", { value: "", children: "-- Ch\u1ECDn l\u1EDBp h\u1ECDc --" }), _jsx("option", { value: "", children: "Nam" }), _jsx("option", { value: "", children: "N\u1EEF" })] })] })] }), _jsx(PieChartStat, { data: sampleData })] }))] }));
};
export default ParentChildReportLearning;
